kind: Deployment
apiVersion: apps/v1
metadata:
   name: arsenal
spec:
   replicas: 1
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     name: arsenal
   template:
     metadata:
       name: arsenalrocks
       labels:
         name: arsenal
     spec:
      containers:
        - name: arteta
          image: httpd
          ports:
          - containerPort: 80
