kind: Deployment
apiVersion: apps/v1
metadata:
   name: westham
spec:
   replicas: 1
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     name: westham
   template:
     metadata:
       name: westhamrocks
       labels:
         name: westham
     spec:
      containers:
        - name: antony
          image: httpd
          ports:
          - containerPort: 80
