name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl with GitHub Secret
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
        chmod 777 $HOME/.kube/config

    - name: Verify kubectl configuration
      run: |
        kubectl config view

    - name: Delete existing resources (if necessary)
      run: |
        kubectl delete -f deployment/ || true
        kubectl delete -f pods/ || true
        kubectl delete -f services/ || true

    - name: Apply Kubernetes manifests forcefully
      run: |
        kubectl apply -f deployment/ --validate=false
        kubectl apply -f pods/ --validate=false
        kubectl apply -f services/ --validate=false
