name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      run: |
        mkdir -p $HOME/.kube
        cp /home/kube/.kube/config $HOME/.kube/config

    - name: Verify kubectl configuration
      run: |
        kubectl config view

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f deployment/
        kubectl apply -f pods/
        kubectl apply -f servicese/
        kubectl apply -f support.yml
